* модули
  На данный момент есть следующие основные модули:
** timer
     фунциональность полностью аналогична setTimeout и setInterval просто с иным API.
     Данный модуль есть просто потому, что далеко не везде где есть javascript - есть браузерные функции
     работы с таймером.
** storage
     Предоставляет возможность сохранять объекты по ключу, обновлять их частями и извлекать только то, что
     нужно. По сути максимально простая db, максимально архитектурно заточена под  репликацию. Версионная
** http_requester
     Аналог xhr, но кросплатформенный
** http_responder
     Сильно упрощённый вариант web сервера, по api скорее похож на xhr
** ui
     набор модулей для формирования пользовательского интерфейса. Как и все остальный модули, главная задача
     ui быть кросплатформенным, это значит что используя один и тот же api вы можете написать приложение
     для web браузера или обычное desktop приложение. 
*** Compositer
       Основной модуль, реализующий логику ui элементов, способы работы с событиями и анимацию
*** video
       модуль реализующий video элемент
*** dnd
       реализация drag and drop
*** filechooser
       элемент для запрашивания и обработки файлов от пользователя

