* Описание того, что такое удалённый модуль капсулы и как он работает

Удалённый модуль - это модуль, который запущен за пределами капсулы, как самостоятельная сущность. Такой модуль
может работать на другом устройстве, на этом же устройстве, но в другом окружении или даже в том же окружении, что
и сама капсула.
Для взаимодействия с капсулой, удалённый модуль использует протокол http, поверх которого используется простейший
протокол, основанный на http.socket. Для любого удалённоо модуля используется один и тот же протокол, отличается
лишь набор сообщений. Таким образом со стороны капсулы, нужно лишь единожды реализовать remote_module_connector
и он может использоваться для любых удалённых модулей. Поскольку удалённый модуль использует для транспорта http.socket,
а принцип работы http.socket прост, то сам удалённый модуль может включать в себя реализацию модуля и собственную
реализацию http.socket. Это даёт возможность реализовать удалённый модуль для тех платформ, где javascript не поддерживается,
на том языке, который поддерживается платформой или же для платформ, к которым capsule ещё не адаптирована.
Примеры использования удалённого модуля могут быть такими:
+ javame Compositer, реализованный целиком на java, включая собственную реализацию http.socket, таким образом
для отображения приложения на мобильном телефоне нужно минимум ресурсов самого мобильного телефона, он становится в
чистом виде remote ui
+ litewise web Compositer, тот же компосайтер, но используя http.socket релизацию, связывающийся с основной капсулой,
находящейся на сервере, без создания капсулы в браузере. Такой способ максимально освобождает браузер от работы, правда
хорош скорее как пример)
+ static web Compositer on php. Самостоятельная реализация компосайтера на php, включающая в себя собственную
реализацию http.socket для взаимодействия с nodejs капсулой. Даёт возможность легко подключить к приложению способ
отображения на старых и маломощных устройствах(старые браузеры, мобильные телефоны и тд)
