(function(current){current.capsule = (function(current){current.dependencies = (function(current){current.bb_allocator = require('parts/bb_allocator.js');
current.cb_synchronizer = require('parts/cb_synchronizer.js');
current.base32 = require('dependencies/base32.js');
current.utils = require('parts/utils.js');
return current;})({});
current.modules = (function(current){current.uuid = (function(current){current = require('modules/uuid.js');
return current;})({});
current.timer = (function(current){current.js = require('modules/timer.js');
return current;})({});
current.transport = (function(current){current.http = (function(current){current.load=(function(current){ return function(){current = require('modules/transport/http.js');
current.socket_cli = require('modules/transport/http/socket_cli.js');
current.socket_srv = require('modules/tranposrt/http/socket_srv.js');
}})(current);return current;})({});
current = require('modules/transport.js');
current.direct = require('modules/transport/direct.js');
return current;})({});
current.http_requester = require('platforms/nodejs/modules/http_requester.js');
current.http_responder = require('platforms/nodejs/modules/http_responder.js');
current.figa = require('modules/figa.js');
return current;})({});
return current;})({});
current.dsa = (function(current){current.mq = require('dsa_mq/mq.js');
return current;})({});
return current;})({});
